Show article detail
YoshikiWarashina/Kita pull request #10
Opened 2023-07-10 07:34 UTC by YoshikiWarashina

created a function for displaying article details

2023-07-10 07:58 UTC, YoshikiWarashina commented
1. 概要
この実装で行った項目は以下の通りです。

- 記事詳細画面

2. 詳細

- クリックした記事のidを表示し、投稿主、時間、タイトル、内容が取得できるか。

- 改行もしっかりと反映されているか。


3. 関連チケット

https://fullspeed.atlassian.net/browse/QKZA-42

4. 動画

改行を反映させた記事詳細

https://github.com/YoshikiWarashina/Kita/assets/129946179/ace8cb7b-e2d3-41af-88a0-5d2a18fef52a

2023-07-18 14:56 UTC, f-ryoya requested changes

2023-07-18 14:56 UTC, f-ryoya commented on apps/kita/app/Http/Controllers/Article/ArticleController.php
>       * Display the specified resource.
こっちのメソッドはPHPDocが英語になってますね

2023-07-19 02:53 UTC, YoshikiWarashina commented on apps/kita/app/Http/Controllers/Article/ArticleController.php
>       * Display the specified resource.
修正しました。

2023-07-21 00:32 UTC, f-ryoya approved these changes
LGTM!

2023-07-21 05:16 UTC, merged