article edit
YoshikiWarashina/Kita pull request #11
Opened 2023-07-11 02:20 UTC by YoshikiWarashina

created a function for article edit

2023-07-18 14:58 UTC, f-ryoya commented
機能はちゃんと動いてそうですね〜

2023-07-18 15:10 UTC, f-ryoya requested changes

2023-07-18 15:10 UTC, f-ryoya commented on apps/kita/app/Services/ArticleService.php
> +    public function isUserArticle(int $articleId, int $userId)
このメソッド名素晴らしい！
基本的にbool型の返り値が返ってくるメソッドはisかhasのprefixで始まることが多いです
気遣いがはなまるうどん

2023-07-18 15:10 UTC, f-ryoya commented on apps/kita/app/Services/ArticleService.php
> +     * 更新する記事を保存。
句点

2023-07-18 15:10 UTC, f-ryoya commented on apps/kita/app/Services/ArticleService.php
> +    public function saveUpdatedArticle(int $articleId, array $data)
僕ならupdateArticleにしますね、もっと言うとサービスクラスにArticleと名前がついているのでupdateだけでも良かったりする...
まあ、正解はないです

2023-07-18 15:10 UTC, f-ryoya commented on apps/kita/resources/views/articles/edit.blade.php
> +                {!! Form::close() !!}
こちらCSRF対策されてるのか気になりました
ここまで要件は求められてないかもだけど、知っていて損はないはず
多分現状はCSRF対策されてないかな

2023-07-18 15:10 UTC, f-ryoya commented on apps/kita/routes/web.php
> +    Route::put('{article_id}/edit', [ArticleController::class, 'update'])->name('article.update')->middleware('auth:members');
ミドルウェアがグループにできそう
基本グループを使う癖をつけておいた方が、つけないことを忘れない気がします

2023-07-19 02:59 UTC, YoshikiWarashina commented on apps/kita/app/Services/ArticleService.php
> +    public function isUserArticle(int $articleId, int $userId)
ありがとうございます。

2023-07-19 03:11 UTC, YoshikiWarashina commented on apps/kita/app/Services/ArticleService.php
> +     * 更新する記事を保存。
修正しました。

2023-07-19 03:11 UTC, YoshikiWarashina commented on apps/kita/resources/views/articles/edit.blade.php
> +                {!! Form::close() !!}
途中で忘れているのに気付いたので最後まとめてやろうかと思ってました。

2023-07-19 03:13 UTC, YoshikiWarashina commented on apps/kita/routes/web.php
> +    Route::put('{article_id}/edit', [ArticleController::class, 'update'])->name('article.update')->middleware('auth:members');
前のブランチで修正済みなのですが、approveが通ってなかったのでマージして取り込むことは現状できていない状態です。その場合、各ブランチで修正した方が良いのでしょうか。

2023-07-19 03:20 UTC, YoshikiWarashina commented on apps/kita/app/Services/ArticleService.php
> +    public function saveUpdatedArticle(int $articleId, array $data)
updateArticleにしました。

2023-07-21 00:34 UTC, f-ryoya commented on apps/kita/resources/views/articles/edit.blade.php
> +                {!! Form::close() !!}
おけまるです

2023-07-21 00:35 UTC, f-ryoya commented on apps/kita/routes/web.php
> +    Route::put('{article_id}/edit', [ArticleController::class, 'update'])->name('article.update')->middleware('auth:members');
Gitが差分を検知しているってことはこの実装で緑のついたところの修正を行ったということになります
なので、修正加えてるなら直した方が良いと思います

2023-07-21 00:35 UTC, f-ryoya approved these changes
LGTM!

2023-07-21 05:04 UTC, merged