comment registration
YoshikiWarashina/Kita pull request #14
Opened 2023-07-13 06:18 UTC by YoshikiWarashina

後でかく

2023-07-18 15:21 UTC, f-ryoya commented
required時のバリデーションエラーの**コメントは必ず指定してください。** って日本語として変な気がします

2023-07-18 15:22 UTC, f-ryoya requested changes

2023-07-18 15:22 UTC, f-ryoya commented on apps/kita/app/Services/CommentService.php
> +     * 新しいコメントを保存。
句点

2023-07-19 03:35 UTC, YoshikiWarashina commented
> required時のバリデーションエラーのコメントは必ず指定してください。 って日本語として変な気がします

デフォルトのまま使っていたので細かいところの配慮ができていなかったです。
修正しました。
<img width="1344" alt="スクリーンショット 2023-07-19 12 34 22" src="https://github.com/YoshikiWarashina/Kita/assets/129946179/35184e7f-b829-4cba-bab2-171ccc4ddc2b">

2023-07-19 03:37 UTC, YoshikiWarashina commented on apps/kita/app/Services/CommentService.php
> +     * 新しいコメントを保存。
修正しました。

2023-07-21 00:37 UTC, f-ryoya approved these changes
LGTM!

2023-07-21 04:58 UTC, merged