Article delete
YoshikiWarashina/Kita pull request #15
Opened 2023-07-18 06:27 UTC by YoshikiWarashina

後でかく

2023-07-24 09:27 UTC, f-ryoya requested changes

2023-07-24 09:27 UTC, f-ryoya commented on apps/kita/app/Services/ArticleService.php
> +     * 記事を削除。
く、句点

2023-07-25 01:47 UTC, YoshikiWarashina commented on apps/kita/app/Services/ArticleService.php
> +     * 記事を削除。
削除しました

2023-07-26 07:02 UTC, f-ryoya approved these changes

2023-07-26 07:14 UTC, merged