show profile edit page
YoshikiWarashina/Kita pull request #16
Opened 2023-07-19 02:20 UTC by YoshikiWarashina

2023-07-24 09:41 UTC, f-ryoya requested changes

2023-07-24 09:41 UTC, f-ryoya commented on apps/kita/app/Http/Controllers/Article/ArticleController.php
> +     * search(keyword)を受け取り、返ってきた検索結果をview渡す
> search(keyword)

何を受け取ってるのか文章から推測しづらいです
日本語にした方いいかも

> 返ってきた検索結果をview渡す

日本語が変です

2023-07-24 09:41 UTC, f-ryoya commented on apps/kita/routes/web.php
> +Route::put('/profile', [ProfileController::class, 'update'])->name('profile.update')->middleware('auth:members');
auth:membersでミドルウェアをグループしているならばそちらに一緒に入れておいた方が良いと思います
一部はグループで管理して一部は外でってするメリットがあるなら別ですが...
複数のグループでauth:membersを指定しているなら、groupをネスト化してミドルウェアを大きな括り、prefixをその中の小さなグループにするのは良いかもしれません

1番のリスクはミドルウェアをつけ忘れた、もしくはミドルウェアに修正が入ったときにグループの外にあることで変更を忘れることなので

2023-07-25 02:10 UTC, YoshikiWarashina commented on apps/kita/app/Http/Controllers/Article/ArticleController.php
> +     * search(keyword)を受け取り、返ってきた検索結果をview渡す
修正しました。

2023-07-25 02:11 UTC, YoshikiWarashina commented on apps/kita/routes/web.php
> +Route::put('/profile', [ProfileController::class, 'update'])->name('profile.update')->middleware('auth:members');
修正しました。

2023-07-25 07:31 UTC, YoshikiWarashina commented
プロフィールの編集の際、email変更なしでも編集できるようにするため自分自身のメールアドレスの重複制限を排除しました。

そうしないとプロフィールの編集をする際、メールアドレスの変更が必須となってしまうため。

https://github.com/YoshikiWarashina/Kita/assets/129946179/6f6b3f66-f315-458c-9a94-c4db3b0b7adc

2023-07-26 07:04 UTC, f-ryoya commented on apps/kita/app/Http/Controllers/Article/ArticleController.php
> +     * 検索用に入力された値を受け取り、エスケープさせ、返ってきた検索結果をviewに渡す
👍

2023-07-26 07:04 UTC, f-ryoya approved these changes

2023-07-26 07:14 UTC, merged