admin edit
YoshikiWarashina/Kita pull request #18
Opened 2023-07-25 07:20 UTC by YoshikiWarashina

2023-07-26 07:15 UTC, f-ryoya requested changes

2023-07-26 07:15 UTC, f-ryoya commented on apps/kita/app/Http/Controllers/Admin/AdminController.php
> +        return redirect('admin/admin_users/'. $adminId . '/edit')->with('message', '更新処理が完了しました')->with('admin', $admin);
RedirectResponseクラスのwithを見ると、配列にして渡すことで1つのwithで実装できそうです
<img width="747" alt="スクリーンショット 2023-07-26 16 13 44" src="https://github.com/YoshikiWarashina/Kita/assets/103237866/d30c3f13-338d-4e3b-89e1-f2eac88ddee5">

2023-07-26 07:36 UTC, YoshikiWarashina commented on apps/kita/app/Http/Controllers/Admin/AdminController.php
> +        return redirect('admin/admin_users/'. $adminId . '/edit')->with('message', '更新処理が完了しました')->with('admin', $admin);
修正しました。

2023-07-28 00:11 UTC, f-ryoya approved these changes
LGTM!

2023-07-28 01:37 UTC, merged