tag list
YoshikiWarashina/Kita pull request #25
Opened 2023-07-28 10:13 UTC by YoshikiWarashina

2023-08-02 12:43 UTC, f-ryoya requested changes
ロジックに問題はなさそうです

2023-08-02 12:43 UTC, f-ryoya commented on apps/kita/database/factories/TagFactory.php
> +    public function definition()
ここ改行ほしいですね
プロパティ同士やメソッド同士の間は改行があった方が見やすいです
Laravelの中のソースコードもそうなってるんで、多分スタンダード
<img width="1516" alt="スクリーンショット 2023-08-02 21 35 54" src="https://github.com/YoshikiWarashina/Kita/assets/103237866/44710cb5-8b5f-41e7-9348-7b70e70dcc1f">

2023-08-03 02:42 UTC, YoshikiWarashina commented on apps/kita/database/factories/TagFactory.php
> +    public function definition()
修正しました。
こんな感じでusageと出るのであたかも改行できてるように見えるのがちょっとわかりづらいところですねぇ

<img width="375" alt="スクリーンショット 2023-08-03 11 34 36" src="https://github.com/YoshikiWarashina/Kita/assets/129946179/0817dd04-417c-4c6a-9fd9-eeca34a7c05d">

2023-08-04 05:04 UTC, f-ryoya commented on apps/kita/database/factories/TagFactory.php
> +    public function definition()
あ、そうだったんですね
なんの拡張機能だろう、僕のやつでない...

2023-08-04 05:05 UTC, f-ryoya approved these changes
LGTM!

2023-08-04 08:09 UTC, merged