tag registration
YoshikiWarashina/Kita pull request #27
Opened 2023-07-31 09:07 UTC by YoshikiWarashina

2023-08-02 13:03 UTC, f-ryoya requested changes

2023-08-02 13:03 UTC, f-ryoya commented on apps/kita/app/Services/TagService.php
> +    public function saveNewTag(array $data)
saveNewTagという命名をしたということはsaveOldTagがあるor将来的にあるかもしれないことを意図してる気がします
そう考えるとNewという形容詞をつける必要がないかも
saveTagかcreateTagが安牌かな

2023-08-03 03:59 UTC, YoshikiWarashina commented on apps/kita/app/Services/TagService.php
> +    public function saveNewTag(array $data)
修正しました。
saveTagにチェンジしました。確かにsaveTagで命名は十分だと感じました。

2023-08-04 05:07 UTC, f-ryoya approved these changes
LGTM!

2023-08-04 08:05 UTC, merged