tag edit
YoshikiWarashina/Kita pull request #28
Opened 2023-08-01 02:56 UTC by YoshikiWarashina

2023-08-02 13:10 UTC, f-ryoya requested changes

2023-08-02 13:10 UTC, f-ryoya commented on apps/kita/app/Http/Requests/Tag/UpdateRequest.php
> +}
こちらCreateRequestと中身同じ処理ですね
それぞれの責務ごとにクラスやメソッドを作るのは良いことである一方、共通化を行わないことはそれはそれでコードの保守性を悪化させます
全く同じロジックでかつタグをDBに格納する時のバリデーションという意味で、責務は同じなのでまとめてもいいのかなと思います

2023-08-03 06:04 UTC, YoshikiWarashina commented on apps/kita/app/Http/Requests/Tag/UpdateRequest.php
> +}
修正しました。
自分自身のunique (タグ名を変更しなくても更新可能)を排除したため、CreateRequestとUpdateRequestの処理を変えました。

2023-08-04 05:27 UTC, f-ryoya commented on apps/kita/app/Http/Requests/Tag/UpdateRequest.php
> +}
なるほど、1箇所だけ処理が違うわけですね
了解です！

クラスファイルを統一するにはこういうこともできるよってコード添付しますね
(多分以下のコードで動くはず...)
```
public function rules()
    {
        $tagId = $this->route('id');
        $routeName = Request::route()->getName();
        $uniqueRule = match ($routeName) {
             'tag.create' => 'unique:article_tags,name',
             'tag.update' => Rule::unique('article_tags', 'name')->ignore($tagId),
       }

        return [
            'tag_name' => ['required', 'string', 'max:20', $uniqueRule],
        ];
    }
```

2023-08-04 05:28 UTC, f-ryoya commented on apps/kita/app/Http/Requests/Tag/UpdateRequest.php
> +}
エンジニアなんでこういう小細工してみたいなって書いたものなので、実際にはやってる中身が違うなら無理に1つのクラスにしなくていいと思うんで現状で大丈夫です！

2023-08-04 08:05 UTC, merged

2023-08-07 02:49 UTC, YoshikiWarashina commented on apps/kita/app/Http/Requests/Tag/UpdateRequest.php
> +}
ありがとうございます。
面白いコードで見たことないものでした。勉強になります。