migration fix
YoshikiWarashina/Kita pull request #29
Opened 2023-08-01 05:26 UTC by YoshikiWarashina

2023-08-02 13:15 UTC, f-ryoya commented
> これはunsigned big intを表すため、
実際のテーブル定義とは異なっていた。

これ自分見逃してましたね、申し訳ない
ちなみにどうして要件定義をした人はbigintではなくintを選択したと思いますか？

2023-08-02 13:26 UTC, f-ryoya commented
> あとはdelete_atがsoftDeletesになっていたが、modelでuse softDeletesすれば適用できるため

Model側でトレイト使うよりmigrationファイルで論理削除の責務持たせた方がテーブル定義を直に反映するmigrationファイルとの相性が良さそうで、Modelは開発者が気をつけないと論理削除のトレイトを利用するの忘れちゃう気がするって思いましたがまあどっちでもいいのかな(少なくともLaravelが提供してるってことは、そういう使い方を想定してるってことだしね)

2023-08-02 13:26 UTC, f-ryoya requested changes

2023-08-02 13:26 UTC, f-ryoya commented on apps/kita/database/migrations/2023_06_28_055142_create_members_table.php
>              $table->timestamp('updated_at')->nullable();
自分Laravel8のmigrationの仕様そんな分かってなかったんですが、調べたら$table->timestamp();だけでcreated_atとupdated_atがカラムに含まれるようですね

<img width="1075" alt="スクリーンショット 2023-08-02 22 20 17" src="https://github.com/YoshikiWarashina/Kita/assets/103237866/cbf31f97-9a84-4c57-b32c-7d2c0277403b">

2023-08-02 13:26 UTC, f-ryoya commented on apps/kita/database/migrations/2023_06_29_053420_create_admin_users_table.php
>              $table->timestamp('updated_at')->nullable();
memberのmigrationファイルと同じ

2023-08-03 06:11 UTC, YoshikiWarashina commented
> ちなみにどうして要件定義をした人はbigintではなくintを選択したと思いますか？

int(4バイト)からbigint(8バイト)間の値を使用することが考え辛いことが考えられます。
intで十分であるためbigintを準備してしまうとデータベースのパフォーマンス低下につながることが考えられると思います。

2023-08-03 06:54 UTC, YoshikiWarashina commented on apps/kita/database/migrations/2023_06_28_055142_create_members_table.php
>              $table->timestamp('updated_at')->nullable();
修正しました。

2023-08-03 06:55 UTC, YoshikiWarashina commented on apps/kita/database/migrations/2023_06_29_053420_create_admin_users_table.php
>              $table->timestamp('updated_at')->nullable();
修正しました。

2023-08-04 05:34 UTC, f-ryoya commented
> int(4バイト)からbigint(8バイト)間の値を使用することが考え辛いことが考えられます。

bigintの場合、値自身は全て8バイトで表現されるので4バイトと8バイトの間の値というのはちょっと違うかもしれません

> intで十分である

何をもってintで十分と思いましたか？

> データベースのパフォーマンス低下につながる

これは適切な解釈ですね👍

2023-08-04 05:36 UTC, f-ryoya commented
> テーブル要件に忠実に従わせていただいています

テーブル要件にはModelかMigrationのどちらで論理削除を実装するか書いていないので、関係ないかなと思います

2023-08-04 05:37 UTC, f-ryoya approved these changes
LGMT!

2023-08-04 08:04 UTC, merged

2023-08-07 04:46 UTC, YoshikiWarashina commented
> bigintの場合、値自身は全て8バイトで表現されるので4バイトと8バイトの間の値というのはちょっと違うかもしれません

これはすみません。自分の意図していたことを違うことが伝わってしまってるみたいです。以下の方がより詳しく説明しているかもです。

> intで十分である

unsigned intの時点で4,294,967,295のデータが使えます。単純に記事投稿アプリ程度であればこれより多いデータを必要とすることは考えずらいかなと思っています。逆に使いもしないほどのデータ容量を確保しておくと、データベースのパフォーマンス低下につながると思っています。

2023-08-07 05:17 UTC, f-ryoya commented
> unsigned intの時点で4,294,967,295のデータが使えます。単純に記事投稿アプリ程度であればこれより多いデータを必要とすることは考えずらいかなと思っています。逆に使いもしないほどのデータ容量を確保しておくと、データベースのパフォーマンス低下につながると思っています。

それそれそれです👍
自分も同じ認識です！