admin user list
YoshikiWarashina/Kita pull request #3
Opened 2023-06-30 04:34 UTC by YoshikiWarashina

created a listing function for admin

2023-07-04 00:53 UTC, f-ryoya requested changes

2023-07-04 00:53 UTC, f-ryoya commented on apps/kita/app/Http/Controllers/admin/AdminController.php
> +namespace App\Http\Controllers\admin;
adminディレクトリがローワーキャメルケースになってますね
他のディレクトリに対応させてアッパーキャメルケースにする必要がありそうです

2023-07-04 00:53 UTC, f-ryoya commented on apps/kita/app/Http/Controllers/admin/AdminController.php
> +    public function index()
他のメソッドもそうですが、一緒に働くエンジニアや将来の自分に対してPHPDocでメソッドについてまとめると良いと思います
https://tech-blog.rakus.co.jp/entry/20210326/php

2023-07-04 00:53 UTC, f-ryoya commented on apps/kita/app/Models/Admin.php
> +    use HasApiTokens, HasFactory, Notifiable;
HasApiTokensトレイトはなぜ必要なんですか？
PRのdescriptionに記載していただきたいです

2023-07-04 00:53 UTC, f-ryoya commented on apps/kita/resources/views/admin/admin_users/create.blade.php
> +{{--        {!! Form::open(['route' => 'admin_users.store', 'method' => 'POST']) !!}--}}
ソースコードにコメントアウトを残すのは負債になるのであまり良くないです
どうしても残したいならばTODOコメント等を残した方が良いと思います

2023-07-04 00:53 UTC, f-ryoya commented on apps/kita/routes/web.php
> +    Route::view('/admin_users', 'admin/admin_users')->middleware('auth:admin');
こちらディレクトリ構造について、admin配下であればファイル名がusersだけでも名前空間からbladeファイルのドメインは絞れる気がするのですがいかがでしょうか？
admin/{admin_}users

2023-07-04 01:10 UTC, f-ryoya commented
> adminユーザーでログイン成功後、adminユーザーを表示するようにしている。ページネーションももうけている。
今までは独断でマージしてしまっていたため、このブランチはadminユーザーの一覧表示のみですが、
ログイン側、新規登録のチェックもお願いいたします。

概要におけるこちらの文章について、1つ1つの文章で伝える意図を絞ってかけると良いかもです
現時点では詳細に動画が添付されていることで概要の意図が汲み取れますが、概要が詳細の内容に依存して意味を成している気がします

例えば以下のような感じです
```
この実装で行った変更は以下です
- adminユーザーのログイン機能
  - ログイン後はadminユーザー一覧画面へ遷移
    - 表示数は6
- adminユーザーの新規登録機能
```

2023-07-04 01:37 UTC, YoshikiWarashina commented on apps/kita/app/Models/Admin.php
> +    use HasApiTokens, HasFactory, Notifiable;
モデル内でコードを書いているうちにごちゃごちゃになってしまい、記事で参考にしたものをコピペして変更部分を変えたので、ただ単に消し忘れです。申し訳ありません。

2023-07-04 01:39 UTC, YoshikiWarashina commented on apps/kita/routes/web.php
> +    Route::view('/admin_users', 'admin/admin_users')->middleware('auth:admin');
こちら意図としては、URLと同じような構造でディレクトリを作っておけば自分としてはわかりやすいかなと思いました。

2023-07-04 12:50 UTC, f-ryoya requested changes

2023-07-04 12:50 UTC, f-ryoya commented on apps/kita/app/Http/Controllers/admin/AdminController.php
> +namespace App\Http\Controllers\admin;
ディレクトリ自体をアッパーキャメルケースにするっていう意図でした
![スクリーンショット 2023-07-04 21 47 15](https://github.com/YoshikiWarashina/Kita/assets/103237866/9ca15727-2971-49ed-829c-312b9546f529)

2023-07-04 12:53 UTC, f-ryoya requested changes

2023-07-04 12:53 UTC, f-ryoya commented on apps/kita/routes/web.php
> +    Route::view('/admin_users', 'admin/admin_users')->middleware('auth:admin');
ということはURLも同様にadminが冗長的な気がするのですがいかがでしょうか？

2023-07-05 09:59 UTC, YoshikiWarashina commented
１.概要
この実装で行った項目は以下の通りです。

- レビューの修正

2.詳細

- ディレクトリ admin　から Admin　への修正

- admin_users/create.blade.phpに記載のコメントアウトにTODOコメントを記載。
 
- 本ブランチ該当箇所のPHP Doc記載

- HasApiTokens 削除

- routingの冗長化に関してですが、ここでのURLはあくまで要件に従った次第で自分が考えたURLではないです。またファイルのディレクトリ構造はそれをベースに似たような配置になるようにしています。


3.関連チケット

https://fullspeed.atlassian.net/browse/QKZA-35

2023-07-05 10:06 UTC, f-ryoya commented
> あくまで要件に従った次第で自分が考えたURLではないです
 なるほど了解です

かなり余談ですが、ダメな要件が流れてきたときにNoが言えるレベルにエンジニアとしてプロフェッショナルであってください、マジで余談です

2023-07-05 10:06 UTC, f-ryoya commented
LGTM!

2023-07-05 10:07 UTC, f-ryoya approved these changes

2023-07-05 10:07 UTC, f-ryoya approved these changes
LGTM

2023-07-13 02:52 UTC, merged