article list with tag
YoshikiWarashina/Kita pull request #31
Opened 2023-08-02 08:22 UTC by YoshikiWarashina

2023-08-04 05:38 UTC, f-ryoya commented
機能は問題なさそうですね！

2023-08-04 05:43 UTC, f-ryoya requested changes
Seederいいですね！
意図した感じで実装されてます👍

2023-08-04 05:43 UTC, f-ryoya commented on apps/kita/app/Http/Controllers/Article/ArticleController.php
> +
不要な改行

2023-08-04 05:43 UTC, f-ryoya commented on apps/kita/database/seeders/ArticlesSeeder.php
> +        });
createメソッドの後に直接eachメソッド繋げられる気がします

2023-08-04 08:23 UTC, YoshikiWarashina commented on apps/kita/app/Http/Controllers/Article/ArticleController.php
> +
修正しました。

2023-08-04 08:23 UTC, YoshikiWarashina commented on apps/kita/database/seeders/ArticlesSeeder.php
> +        });
修正しました。

2023-08-07 05:52 UTC, f-ryoya approved these changes
LGTM!

2023-08-08 01:53 UTC, merged