redirect for unauthenticated users
YoshikiWarashina/Kita pull request #39
Opened 2023-08-21 03:26 UTC by YoshikiWarashina

2023-08-23 02:17 UTC, f-ryoya requested changes

2023-08-23 02:17 UTC, f-ryoya commented on apps/kita/app/Http/Controllers/Admin/LoginController.php
>          logout as performLogout;                            //追記
追記のコメントアウト消していいと思います
Githubで差分が見れるようになっており、差分をアピールする必要はないです🙅‍♀️

2023-08-23 02:17 UTC, f-ryoya commented on apps/kita/app/Http/Middleware/Authenticate.php
> +            }
if文のネスト化は可読性を下げるので、できるだけ避けたいです
対策として一般的には早期returnが使われています

あとこの前[#fullspeed-engineers](https://fullspeed.slack.com/archives/C04M23HCPHQ/p1692328945382919?thread_ts=1692326421.439969&cid=C04M23HCPHQ)でif文の条件式は関数にして外に出すというものがありました
今回は条件が1つなのでそこまで気にしなくてもいいかもですが、この辺りも可読性を意識するといいと思います

2023-08-23 02:19 UTC, f-ryoya commented on apps/kita/app/Http/Controllers/Admin/LoginController.php
>          logout as performLogout;                            //追記
こっちのPRで消えてましたね💦
https://github.com/YoshikiWarashina/Kita/pull/40/files

2023-08-24 03:15 UTC, YoshikiWarashina commented on apps/kita/app/Http/Middleware/Authenticate.php
> +            }
ネストがないやり方で書いてみました。
early return についていろんな書き方を記した記事があったので、以下のような書き方でいいのか確認させてください。

`if ($request->expectsJson()) {
    return null;
}

if ($request->is('admin/*')) {
    return route('admin.login');
}

return route('login');`

2023-08-24 07:04 UTC, miokanedaC commented on apps/kita/app/Http/Middleware/Authenticate.php
> +            }
↑でいいと思います。elseifとか使わずに。こ、、、細かいですが。

2023-08-24 07:35 UTC, YoshikiWarashina commented on apps/kita/app/Http/Middleware/Authenticate.php
> +            }
修正しました

2023-08-24 07:45 UTC, miokanedaC approved these changes
![image](https://github.com/YoshikiWarashina/Kita/assets/84494562/fe2b205b-6d11-456e-9595-687b87868cd5)

2023-08-25 06:40 UTC, f-ryoya approved these changes
![92gfs4nnfyvzsp4fg8rbu22izqdn](https://github.com/YoshikiWarashina/Kita/assets/103237866/b2c421df-983a-45b7-bd87-b99b603fdcad)

2023-08-25 06:57 UTC, merged