user page design and some fixations
YoshikiWarashina/Kita pull request #4
Opened 2023-07-04 03:22 UTC by YoshikiWarashina

1. 概要

この実装で行った項目は以下の通りです。
- user側のデザインを全ページ作成
- 前回のプルリクエストに対しての修正
　　　- HasApiTokens削除
　　　- メソッドにPHP Doc追加 (追加漏れがあるので後で追加予定)
　　　- adminディレクトリのAdminへの修正

2.詳細

- user側のデザインをbootstrapでresponsiveデザインで作成。
- ページ遷移やフォームやテキストファイルなどの細かいところは機能で必要になった時に変更する。

3.関連チケット

- https://fullspeed.atlassian.net/jira/software/projects/QKZA/boards/223?selectedIssue=QKZA-34

4.画像

ログイン画面
<img width="1688" alt="スクリーンショット 2023-07-04 12 12 49" src="https://github.com/YoshikiWarashina/Kita/assets/129946179/4b60ff3b-84f6-476d-a329-b549e6f7f20d">

記事一覧
<img width="1681" alt="スクリーンショット 2023-07-04 12 14 24" src="https://github.com/YoshikiWarashina/Kita/assets/129946179/3e179928-a0ac-4dec-91db-060eefedfaa8">

記事投稿
<img width="1685" alt="スクリーンショット 2023-07-04 12 15 31" src="https://github.com/YoshikiWarashina/Kita/assets/129946179/c8e2b917-c792-40d8-9f43-54ab52e196b3">

記事詳細
<img width="1600" alt="スクリーンショット 2023-07-04 12 16 57" src="https://github.com/YoshikiWarashina/Kita/assets/129946179/554365ae-677e-47a7-baa9-79dc056f144f">

会員登録
<img width="1606" alt="スクリーンショット 2023-07-04 12 18 20" src="https://github.com/YoshikiWarashina/Kita/assets/129946179/c9497842-7392-435f-a2da-363dcc9c6ab5">

記事編集
<img width="1631" alt="スクリーンショット 2023-07-04 12 19 26" src="https://github.com/YoshikiWarashina/Kita/assets/129946179/ce8d4753-256e-4df1-b992-bd119f30ffcc">

プロフィール編集
<img width="1611" alt="スクリーンショット 2023-07-04 12 20 47" src="https://github.com/YoshikiWarashina/Kita/assets/129946179/84ba3103-fbc8-430e-9fa0-f187fc3d689a">

パスワード変更
<img width="1620" alt="スクリーンショット 2023-07-04 12 21 36" src="https://github.com/YoshikiWarashina/Kita/assets/129946179/563c28f1-d785-4cbb-8115-5f9c4e962dde">

2023-07-04 12:58 UTC, f-ryoya commented
> user側のデザインを全ページ作成
全ページとは何でしょう？

2023-07-04 13:07 UTC, f-ryoya requested changes

2023-07-04 13:07 UTC, f-ryoya commented on apps/kita/app/Services/AdminService.php
> +    }
PHPDocあるといいですね

2023-07-04 13:07 UTC, f-ryoya commented on apps/kita/resources/views/articles/detail.blade.php
> +                            <p>内容もここにバーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー表示</p>
動的コンテンツを後から実装するためにあえて変数を使わず静的にしてる感じですかね
チケットの粒度の分け方としてはよいですね

2023-07-04 13:07 UTC, f-ryoya commented on apps/kita/app/Http/Controllers/Admin/AdminController.php
> +        $admins = $adminService->getAdminUsers();
ロジックを別クラスに切り分けられているのはよいですね
自分だったらDBアクセスロジックをRepositoryクラスに定義し、その後の加工等をServiceクラスに定義するかなと思います
現時点でロジックが複雑なわけではないので、わざわざRepositoryクラスを作る必要はないかもです(後学のため)

2023-07-05 11:32 UTC, YoshikiWarashina commented on apps/kita/app/Services/AdminService.php
> +    }
こちらに関しては、ミスで本来ならデザインのみを行うブランチですが、ここで機能を作ってしまいました。
ここのPHPDocに関しては別のPRで行います。また、その際はその旨を記載しておきます。

2023-07-06 02:36 UTC, YoshikiWarashina commented
１.概要
この実装で行った項目は以下の通りです。

- レビューの修正



2.詳細

- 前のコミットで記載済みだが、本来はデザインのみを行うブランチで機能を作ってしまった。
　そのため辻褄を合わせるため、修正をここで行った。

- 修正箇所は、admin一覧表示用のPHPDocの追加のみ

3.関連チケット

https://fullspeed.atlassian.net/browse/QKZA-34

2023-07-06 03:27 UTC, f-ryoya approved these changes
LGTM!

2023-07-07 12:28 UTC, f-ryoya approved these changes

2023-07-07 12:29 UTC, f-ryoya commented
LGTM!

2023-07-13 02:52 UTC, merged