independent logout
YoshikiWarashina/Kita pull request #40
Opened 2023-08-21 10:28 UTC by YoshikiWarashina

2023-08-23 02:18 UTC, f-ryoya commented
> ログインしていない場合、記事投稿・プロフィール変更・ログアウトボタンを削除

"削除"ではなく"非表示"ですね

2023-08-23 02:30 UTC, f-ryoya commented
<img width="347" alt="スクリーンショット 2023-08-23 11 28 16" src="https://github.com/YoshikiWarashina/Kita/assets/103237866/bd37d56e-db75-4bc7-b020-1ad4c1c7b1c9">
このディレクトリ構成気になりました
Adminに入ってるLoginControllerっておそらくAuthのスコープにあるべきな気がします
Member側のAuthと同じ階層に並べるのはちょっと違うかも

2023-08-23 08:01 UTC, f-ryoya requested changes

2023-08-23 08:01 UTC, f-ryoya commented on apps/kita/app/Http/Controllers/Admin/LoginController.php
> +     * @return　\Illuminate\Http\Response|\Illuminate\Http\JsonResponse|\Illuminate\Http\RedirectResponse
できればこの辺のnamespaceはクラスファイルの初めにuseでnamespaceをインポートしておくと良いと思います
長いですし、同クラス内で再度利用するときにまた記述する必要が出てくるので💦

2023-08-23 08:01 UTC, f-ryoya commented on apps/kita/app/Http/Controllers/Admin/LoginController.php
> +            : redirect()->route('admin_users.index');
Laravelフレームワークのお作法に則るのなら、プロパティの$redirectToをオーバーライドするのが良さそうです
<img width="533" alt="スクリーンショット 2023-08-23 14 53 25" src="https://github.com/YoshikiWarashina/Kita/assets/103237866/6833d0ba-1c1f-4299-9e68-d684906b42e0">
<img width="662" alt="スクリーンショット 2023-08-23 14 53 34" src="https://github.com/YoshikiWarashina/Kita/assets/103237866/76d1200b-066e-42c1-9599-cfae2cb24acb">

2023-08-23 08:01 UTC, f-ryoya commented on apps/kita/app/Http/Controllers/Admin/LoginController.php
> +        return redirect()->route('admin.login.form');
こちら、元のAuthenticatesUsersトレイトにあるlogoutメソッドをオーバーライドされてると思うのですが
```
$request->session()->invalidate();
$request->session()->regenerateToken();
```
が書かれていません
<img width="465" alt="スクリーンショット 2023-08-23 14 58 06" src="https://github.com/YoshikiWarashina/Kita/assets/103237866/96d51131-7608-4fb3-a934-e319bb05a059">


これだと本当にログアウトできてるのか確認する必要があります

2023-08-23 08:01 UTC, f-ryoya commented on apps/kita/app/Http/Controllers/Auth/LoginController.php
> +            : redirect()->route('article.index');
これもadminと一緒です

2023-08-23 08:01 UTC, f-ryoya commented on apps/kita/app/Http/Controllers/Auth/LoginController.php
> +        $this->guard()->logout();
adminと一緒

2023-08-23 08:01 UTC, f-ryoya commented on apps/kita/app/Http/Controllers/Admin/LoginController.php
> +
```suggestion
*
     * @var string
     */
    protected $redirectTo = route('admin_users.index');

```

2023-08-23 08:01 UTC, f-ryoya commented on apps/kita/app/Http/Controllers/Admin/LoginController.php
> +            : redirect()->route('admin_users.index');
```suggestion
return $request->wantsJson()
                    ? new JsonResponse([], 204)
                    : redirect()->intended($this->redirectPath());```

2023-08-23 08:01 UTC, f-ryoya commented on apps/kita/app/Http/Controllers/Admin/LoginController.php
> +        return redirect()->route('admin.login.form');
```suggestion
        $this->guard()->logout();

        return $request->wantsJson()
            ? new JsonResponse([], 204)
            : redirect(route('admin.login.form'));
```

2023-08-23 08:01 UTC, f-ryoya commented on apps/kita/routes/web.php
>  });
ルート名のプレフィックスもまとめられます
https://readouble.com/laravel/8.x/ja/routing.html#:~:text=%E3%81%AB%E4%B8%80%E8%87%B4%0A%20%20%20%20%7D)%3B%0A%7D)%3B-,%E3%83%AB%E3%83%BC%E3%83%88%E5%90%8D%E3%81%AE%E3%83%97%E3%83%AC%E3%83%95%E3%82%A3%E3%83%83%E3%82%AF%E3%82%B9,-name%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89%E3%82%92

2023-08-23 08:02 UTC, f-ryoya commented on apps/kita/app/Http/Controllers/Admin/LoginController.php
> +        return redirect()->route('admin.login.form');
meetで確認した感じだとどうやら良さそう

2023-08-23 11:03 UTC, YoshikiWarashina commented on apps/kita/routes/web.php
>  });
修正しました

2023-08-23 11:03 UTC, YoshikiWarashina commented on apps/kita/app/Http/Controllers/Admin/LoginController.php
> +        return redirect()->route('admin.login.form');
修正しました

2023-08-23 11:05 UTC, YoshikiWarashina commented on apps/kita/app/Http/Controllers/Admin/LoginController.php
> +            : redirect()->route('admin_users.index');
intendedが厄介なので、今のところはlogoutのredirect(route())の書き方に揃えています。

2023-08-23 11:06 UTC, YoshikiWarashina commented on apps/kita/app/Http/Controllers/Admin/LoginController.php
> +
<img width="492" alt="スクリーンショット 2023-08-23 20 05 50" src="https://github.com/YoshikiWarashina/Kita/assets/129946179/95fcbe0b-269d-40a9-ab4b-b6e96451eac0">

こんな感じになったので、ここの修正は保留にしています

2023-08-24 05:41 UTC, miokanedaC reviewed
@YoshikiWarashina 
slackで質問あった件のコメント書きました。

2023-08-24 05:41 UTC, miokanedaC commented on apps/kita/app/Http/Controllers/Admin/LoginController.php
> +            : redirect()->route('admin_users.index');
@YoshikiWarashina 
もし強制的にログイン後特定のページにredirectさせるのであれば、

1. sendLoginResponseをLoginControllerから消しす
2. authenticatedの関数をLoginController書くoverrideして返り値を指定してあげる `return $this->redirectPath(); `
※ redirectToをoverrideしていることを前提としてます。


もしintendedの処理で完結させるのであればredirectToのoverrideをしてsendLoginResponseをLoginControllerから消せばできるかな。この際の確認方法としては、シークレット画面で直接ログインページを直叩きしてからログインして、redirectToで指定したページに飛んでるかで確認できるかと思います。

2023-08-24 07:11 UTC, miokanedaC requested changes
1点だけコメントしました。

2023-08-24 07:11 UTC, miokanedaC commented on apps/kita/app/Http/Controllers/Admin/Auth/LoginController.php
> +        logout as performLogout;
これはいらないですかね。

2023-08-24 07:16 UTC, YoshikiWarashina commented on apps/kita/app/Http/Controllers/Admin/Auth/LoginController.php
> +        logout as performLogout;
修正しました。

2023-08-24 07:44 UTC, miokanedaC approved these changes
動作確認 / 細かな確認はしてないですがいいと思います。
![image](https://github.com/YoshikiWarashina/Kita/assets/84494562/24b9100a-9ef0-40fb-9649-cb914004ad7e)

2023-08-25 06:43 UTC, f-ryoya approved these changes
![oyabaka_lgtm](https://github.com/YoshikiWarashina/Kita/assets/103237866/6eff3d74-dc52-49bc-b047-5cfa439c906a)

2023-08-25 06:54 UTC, merged