install browserify
YoshikiWarashina/Kita pull request #41
Opened 2023-08-23 03:14 UTC by YoshikiWarashina

2023-08-30 07:12 UTC, miokanedaC requested changes
@YoshikiWarashina 
丁寧ですね。コメントも入ってるので読みやすかったです。
一部なんで？的な質問しているのでみて返事ください

2023-08-30 07:12 UTC, miokanedaC commented on apps/kita/resources/views/layouts/admin.blade.php
> +    <script src="{{ asset('js/delete.articles.js') }}" defer></script>
必要ですか？

2023-08-30 07:12 UTC, miokanedaC commented on apps/kita/resources/views/layouts/app.blade.php
> +    <script src="{{ asset('js/delete.articles.js') }}" defer></script>
必要ですか？

2023-08-30 07:12 UTC, miokanedaC commented on apps/kita/resources/js/remember.checkbox.js
> +        const articleId = checkbox.getAttribute('data-article-id');
https://caniuse.com/?search=data-
data属性昔サポートされていないブラウザーあった気がしたんだけど、ほぼサポートされてますね。

2023-08-30 07:12 UTC, miokanedaC commented on apps/kita/resources/js/remember.checkbox.js
> +document.addEventListener('DOMContentLoaded', function() {
こちらはjqueryではないんですね。

2023-08-30 07:12 UTC, miokanedaC commented on apps/kita/resources/js/delete.articles.js
> +                alert(response.message);
alertにしたんですね。
Controller側でFlash message設定してあげればreloadした後に出そうな気がします。

2023-08-30 07:12 UTC, miokanedaC commented on apps/kita/resources/js/app.js
> +import './remember.checkbox';
これをapp.jsに入れてdeleteを入れてない理由ってなんですか？

2023-08-30 07:34 UTC, f-ryoya requested changes
フロントは金田さんがみてそうなのでバックエンドだけ確認しました

2023-08-30 07:34 UTC, f-ryoya commented on apps/kita/app/Http/Controllers/Article/ArticleController.php
> +    public function myArticles(ArticleService $articleService)
一般的にメソッドはインスタンスの振る舞いを定義したものなので、動詞から命名するのが良いかと思います

2023-08-30 08:00 UTC, YoshikiWarashina commented on apps/kita/resources/views/layouts/admin.blade.php
> +    <script src="{{ asset('js/delete.articles.js') }}" defer></script>
不要でした。

2023-08-30 08:00 UTC, YoshikiWarashina commented on apps/kita/resources/views/layouts/app.blade.php
> +    <script src="{{ asset('js/delete.articles.js') }}" defer></script>
不要でした。

2023-08-30 08:37 UTC, YoshikiWarashina commented on apps/kita/resources/js/remember.checkbox.js
> +document.addEventListener('DOMContentLoaded', function() {
修正しました。
同じくjQueryが反応していなかったため、jQueryでないやり方でやってました。

2023-08-30 08:39 UTC, YoshikiWarashina commented on apps/kita/resources/js/delete.articles.js
> +                alert(response.message);
他の機能同様フラッシュメッセージで出すようにしました。

https://github.com/YoshikiWarashina/Kita/assets/129946179/33f4055f-a5f6-42fb-bb6a-cbdd62160b17

2023-08-30 08:41 UTC, YoshikiWarashina commented on apps/kita/resources/js/app.js
> +import './remember.checkbox';
slackで回答済みです

2023-08-30 08:42 UTC, YoshikiWarashina commented on apps/kita/app/Http/Controllers/Article/ArticleController.php
> +    public function myArticles(ArticleService $articleService)
listMyArticlesに直してたつもりが、command Zで戻り過ぎてこのまま出してしまっていました。

修正しました。

2023-08-30 08:43 UTC, YoshikiWarashina commented on apps/kita/resources/views/layouts/admin.blade.php
> +    <script src="{{ asset('js/delete.articles.js') }}" defer></script>
不要でした。

2023-08-30 08:43 UTC, YoshikiWarashina commented on apps/kita/resources/views/layouts/app.blade.php
> +    <script src="{{ asset('js/delete.articles.js') }}" defer></script>
不要でした。

2023-08-31 00:45 UTC, f-ryoya approved these changes
LGTM

2023-08-31 01:13 UTC, miokanedaC requested changes
@YoshikiWarashina 
良さそうです。jsの読み込みがダブルで発生しているので、避けてください。
こちら消してもらったら特に問題はないかなって思います。
ちなみに、autoloadの方でも試してみました？

2023-08-31 01:13 UTC, miokanedaC commented on apps/kita/resources/views/layouts/admin.blade.php
> +    <script src="{{ asset('js/delete.articles.js') }}" defer></script>
消し忘れですか？？

2023-08-31 01:13 UTC, miokanedaC commented on apps/kita/resources/views/layouts/app.blade.php
> +    <script src="{{ asset('js/delete.articles.js') }}" defer></script>
消し忘れですね。w

2023-08-31 01:39 UTC, miokanedaC approved these changes
LGTM

2023-08-31 01:51 UTC, merged