new admin registration
YoshikiWarashina/Kita pull request #5
Opened 2023-07-04 07:42 UTC by YoshikiWarashina

1. 概要
この実装で行った項目は以下の通りです。

- admin userの新規登録機能

2.詳細

- 新規登録ボタンを押したら登録ページに遷移する。
- 必要な情報を入力し、登録ボタンを押す。(バリデーションに引っかかれれば、エラー文表示)
- 登録完了後、登録成功メッセージと共に編集ページへ遷移。

3.関連チケット
https://fullspeed.atlassian.net/jira/software/projects/QKZA/boards/223?selectedIssue=QKZA-36

4.動画

成功例
https://github.com/YoshikiWarashina/Kita/assets/129946179/b2332be0-2e7c-448c-9862-43903a8302e0
<img width="598" alt="スクリーンショット 2023-07-04 16 40 19" src="https://github.com/YoshikiWarashina/Kita/assets/129946179/5cca57d1-0d85-4ccb-b678-9ea8c70ec0cd">

失敗例
https://github.com/YoshikiWarashina/Kita/assets/129946179/52ee60db-2989-4846-b453-8d5aa963bbcb

2023-07-04 13:10 UTC, f-ryoya commented
> 登録後のパスワードが剥き出しなのは後ほど直します。

パスワードはハッシュ化されたものが表示されているような気がします
なのでセキュリティ上はそこまで問題ないです

ただご自身が入力したものと異なるハッシュ化されたパスワードが、ユーザー編集の画面に表示されるのはユーザーの混乱を招くかなと思います

2023-07-04 13:11 UTC, f-ryoya commented
> 失敗例

失敗例の動画ですが、バリデーションの種類はいくつもあるため全てをケースを動画で共有しないと本当にバリデーションが実装できてるかは確認できないです

2023-07-05 01:13 UTC, f-ryoya requested changes

2023-07-05 01:13 UTC, f-ryoya commented on apps/kita/app/Services/AdminService.php
> +    public function getNewAdmin(array $data)
PHPDoc

2023-07-05 01:13 UTC, f-ryoya commented on apps/kita/app/Http/Controllers/Admin/AdminController.php
> +        $admin->save();
モデルインスタンスを作るロジックとsaveを行うロジックを別クラスで行うのはコードの低凝集を引き起こしてる気がします
またgetNewAdminという命名ですが、処理を見る感じモデルへのsetterのようで中の振る舞いとメソッド名が一致してないかもです
もし、50行目でレコードのIDを取得したいのであればcreateメソッドを使うと、返り値がモデルインスタンスとして返ってくるのでおすすめですよ〜

2023-07-05 01:13 UTC, f-ryoya commented on apps/kita/app/Services/AdminService.php
> +        $admin->password = Hash::make($data['password']);
モデルインスタンスのプロパティの書き換えを直で行うのは見たことなかったです
同様の処理をする場合はfill+saveを自分だったら使います
そうすることでModelクラスで定義した$fillableや$guardedによって複数代入を保護できます
https://readouble.com/laravel/4.2/ja/eloquent.html#:~:text=%E6%96%B0%E3%81%97%E3%81%84%E3%83%A2%E3%83%87%E3%83%AB%E3%82%92%E4%BD%9C%E6%88%90,%E3%81%97%E3%81%A6%E3%81%8F%E3%81%A0%E3%81%95%E3%81%84

逆にModelクラスで$fillableもしくは$guardedを定義した上で、既存のコードの処理を行った場合複数代入の保護は行われるのか気になります...(もしよければ試していただきたいです)

2023-07-05 02:22 UTC, f-ryoya commented on apps/kita/app/Services/AdminService.php
> +        $admin->password = Hash::make($data['password']);
いや、プロパティ毎に直入れすることありますね
とはいえ、そうしなくても良いならまとめてfillかcreateした方が良いかもです

2023-07-05 11:17 UTC, YoshikiWarashina commented
１.概要
この実装で行った項目は以下の通りです。

- レビューの修正

2.詳細

- save()をAdminServiceクラスに書き写し。

- 同クラスでのfill saveを使っての書き換え。

- PHP Docの付け足し。

- エラーメッセージの日本語文をlang/ja/validation.phpに書き写し。

- バリデーションの失敗前パターン(下記画像)


3.関連チケット

https://fullspeed.atlassian.net/browse/QKZA-36


4 画像

- required失敗

<img width="1319" alt="スクリーンショット 2023-07-05 19 38 42" src="https://github.com/YoshikiWarashina/Kita/assets/129946179/9e6cc1a9-4268-4465-9c4e-851e0d782144">

-指定文字以下、以上

<img width="1343" alt="スクリーンショット 2023-07-05 20 10 29" src="https://github.com/YoshikiWarashina/Kita/assets/129946179/da7ff398-2563-40d6-854a-e25890600099">

- 既存メールアドレス

<img width="1360" alt="スクリーンショット 2023-07-05 20 12 14" src="https://github.com/YoshikiWarashina/Kita/assets/129946179/d7b94ba7-0db5-45bd-8e85-610322d3533f">

- 無効メールアドレス
<img width="1013" alt="スクリーンショット 2023-07-05 20 14 11" src="https://github.com/YoshikiWarashina/Kita/assets/129946179/71f19a1d-69d7-49cb-b417-66bb1e7d4735">

2023-07-10 02:22 UTC, f-ryoya approved these changes
LGTM

2023-07-13 02:51 UTC, merged