article search
YoshikiWarashina/Kita pull request #7
Opened 2023-07-06 06:32 UTC by YoshikiWarashina

1. 概要
この実装で行った項目は以下の通りです。

- 記事の検索

2. 詳細

- タイトルと内容に対して部分一致検索を実装。

- バリデーションは、特殊文字に対して行う。

- 未入力検索を許可し、その際は全ての記事を取得。

3.関連チケット

https://fullspeed.atlassian.net/browse/QKZA-39

4.動画

検索成功

https://github.com/YoshikiWarashina/Kita/assets/129946179/deee4962-5810-4d1f-ab80-77e28868c595

未入力検索

https://github.com/YoshikiWarashina/Kita/assets/129946179/f38d2d10-2e26-4f08-9aab-42d626baa45e

バリデーション失敗(特殊文字)

https://github.com/YoshikiWarashina/Kita/assets/129946179/8061525d-5161-4070-b940-0d1f0696a151

2023-07-06 06:42 UTC, YoshikiWarashina commented
1. 概要

この実装で行った項目は以下の通りです。

- 記事の検索の際のURLの変更 (要件通り)



2. 詳細

- 記事の検索の際のURLの変更 (/articles/search/keyword?=  から /articles?search=)


3. 関連チケット

https://fullspeed.atlassian.net/browse/QKZA-39


4. 画像

<img width="1469" alt="スクリーンショット 2023-07-06 15 41 14" src="https://github.com/YoshikiWarashina/Kita/assets/129946179/6ec48a0e-7421-4671-b213-c74983fdf874">

2023-07-13 03:30 UTC, f-ryoya commented
> 記事の検索の際のURLの変更 (/articles/search/keyword?= から /articles?search=)
この書き方レビューしやすくてありがたいです！

2023-07-13 03:39 UTC, f-ryoya commented
> バリデーションは、特殊文字に対して行う。

特殊文字にバリデーションかけるのは仕様なんですかね？
タイトルに"%"や"#"を使うことって割とあると思います
特殊文字をエスケープさせるという要件の方が一般的な気がします

2023-07-13 07:04 UTC, f-ryoya commented
> 特殊文字に対してエスケープ処理を施す(修正済み)

検索窓に%を入れると%がタイトルに含まれる記事が検索できますか？
できれば動画込みでお願いします

2023-07-18 01:28 UTC, YoshikiWarashina commented
> 検索窓に%を入れると%がタイトルに含まれる記事が検索できますか？
できれば動画込みでお願いします

修正しました。エスケープを実装し、%検索できるようにしました。

画面収録 2023-07-18 10.27.09

2023-07-18 14:36 UTC, f-ryoya commented
> 修正しました。エスケープを実装し、%検索できるようにしました
 
おおすばらしい！！！！👏

2023-07-18 14:36 UTC, f-ryoya commented
このPR概要2つありますね

2023-07-18 14:47 UTC, f-ryoya commented
> ご指摘いただいた検索欄にバリデーションではなくxss対策を実装

検索欄にxss対策を実装とはどういうことでしょうか？

2023-07-18 14:54 UTC, f-ryoya requested changes

2023-07-18 14:54 UTC, f-ryoya commented on apps/kita/app/Services/AdminService.php
> +     * 管理者ユーザーをページネーション込みで取得。
https://github.com/YoshikiWarashina/Kita/pull/9#discussion_r1262288558
以上のコメントで記載したことに反してますね

2023-07-18 14:54 UTC, f-ryoya commented on apps/kita/app/Services/ArticleService.php
> +     * 記事の部分一致検索結果一覧をページネーション込みで取得.
こちらも同様です

2023-07-18 14:54 UTC, f-ryoya commented on apps/kita/app/Services/ArticleService.php
> +    public function getSearchedArticles($keyword)
ロジックがうまく切り分けられてますね！
引数にタイプヒンティングをつけて、引数の型を制限するとより保守性の高いコードになりそうです

2023-07-19 02:22 UTC, YoshikiWarashina commented on apps/kita/app/Services/AdminService.php
> +     * 管理者ユーザーをページネーション込みで取得。
以前のコメントで修正したよりも前にこのブランチは作成していたので、ここに関しては修正できていませんでした。
修正いたしました。

2023-07-19 02:25 UTC, YoshikiWarashina commented on apps/kita/app/Services/ArticleService.php
> +     * 記事の部分一致検索結果一覧をページネーション込みで取得.
修正しました。

2023-07-19 02:25 UTC, YoshikiWarashina commented on apps/kita/app/Services/ArticleService.php
> +    public function getSearchedArticles($keyword)
修正しました。

2023-07-19 02:30 UTC, YoshikiWarashina commented
> このPR概要2つありますね
修正し直しました。

> 検索欄にxss対策を実装とはどういうことでしょうか？
これは無視してください。処理も組み込んでいないです。お恥ずかしい。。。

2023-07-21 00:31 UTC, f-ryoya commented
> これは無視してください。処理も組み込んでいないです。お恥ずかしい。。。

笑
もしかしたらxssについて誤解されてるかもなって思ってのコメントでした、大丈夫です👍

2023-07-21 00:31 UTC, f-ryoya approved these changes
LGTM!

2023-07-21 05:42 UTC, merged