login logout fixation
YoshikiWarashina/Kita pull request #8
Opened 2023-07-07 02:37 UTC by YoshikiWarashina

1. 概要
この実装で行った項目は以下の通りです。

- ログイン、ログアウトでのルーティング修正

2. 詳細
テスト項目は以下のとおりです。

1. ログインした後の画面は一覧にとべるか。
2. デフォルトの/homeにアクセスできないようになっているか
3. ログアウトしたらadminならadmin/userならuserのログイン画面に戻るか
4. ログインしている状態でログインや登録にアクセスしたら一覧に戻るか
5. ログアウトした状態で中に入ろうとするとアクセスできないかどうか (userの場合は全員がアクセスできるようにしてあること)

3. 関連チケット

https://fullspeed.atlassian.net/browse/QKZA-40

4. 動画
項目１(ログインした後の画面は一覧にとべるか。)

・user
https://github.com/YoshikiWarashina/Kita/assets/129946179/b128149c-e51f-4a1a-9e76-e95c9819b4e1

・admin
https://github.com/YoshikiWarashina/Kita/assets/129946179/a3c5a080-0af3-4704-98ed-cb0e7d05f84b

項目２(デフォルトの/homeにアクセスできないようになっているか)

・user
https://github.com/YoshikiWarashina/Kita/assets/129946179/6b724a4d-fb40-4b17-834f-a06e90ddca22

・admin
https://github.com/YoshikiWarashina/Kita/assets/129946179/8a50edf0-e677-41e3-a466-d2eaadab856d

項目３(ログアウトしたらadminならadmin/userならuserのログイン画面に戻るか)

・user
https://github.com/YoshikiWarashina/Kita/assets/129946179/22aed256-7a28-4365-84be-ed9c6632f37c

・admin
https://github.com/YoshikiWarashina/Kita/assets/129946179/c5214640-636a-4c2f-8df5-53d3a00349c9

項目４(ログインしている状態でログインや登録にアクセスしたら一覧に戻るか)

・user

https://github.com/YoshikiWarashina/Kita/assets/129946179/ab7de741-721b-41bf-8351-49b0a3677480

・admin (失敗)　どこが原因なのかご教授いただけると幸いです。

https://github.com/YoshikiWarashina/Kita/assets/129946179/36c235f6-17d7-49d0-b404-5b1a43f14ba8

項目５(ログアウトした状態で中に入ろうとするとアクセスできないかどうか (userの場合は全員がアクセスできるようにしてあること)

・user

https://github.com/YoshikiWarashina/Kita/assets/129946179/47c9f5d5-e2b0-4ddd-9936-95cf93caae60

・admin

https://github.com/YoshikiWarashina/Kita/assets/129946179/5aad9fda-7802-4827-989b-b7511898c817

５.失敗項目

項目４のadmin
認証済みのユーザーのリダイレクトがうまく反映されていない。ご教授お願いいたします。

2023-07-07 12:35 UTC, f-ryoya commented
> admin (失敗)　どこが原因なのかご教授いただけると幸いです。

/loginにつきましてに遷移した際にlogoutの処理が走っているか、/loginのページが認証されているユーザーに関わらず表示されるようになっているかですかね
前者ならlogin画面に遷移する際のロジックを確認してみて、セッション削除等によってサーバー(ローカルPCの場合はPHPコンテナ)内の状態が削除されてるロジックが入ってるかもしれません
後者ならguardの設定がない可能性があります

2023-07-07 12:41 UTC, f-ryoya requested changes

2023-07-07 12:41 UTC, f-ryoya commented on apps/kita/routes/web.php
> +Route::group(['prefix' => ''], function () {
このprefix、空文字ですが必要なんですかね

2023-07-07 12:41 UTC, f-ryoya commented on apps/kita/routes/web.php
>  });
middlewareでRoute::groupかRoute::middlewateするといいかもですね
認証周りのルーティング1つ1つにミドルウェアメソッドを書くのは、書き忘れの恐れがあるので

2023-07-11 03:13 UTC, YoshikiWarashina commented on apps/kita/routes/web.php
> +Route::group(['prefix' => ''], function () {
まとめた方がインデントが揃って綺麗かと思ったのですが、ご指摘いただいたのでやめました。

2023-07-11 03:13 UTC, YoshikiWarashina commented on apps/kita/routes/web.php
>  });
middlewareが必要なもの、不要なもので分割しました。

2023-07-13 07:09 UTC, f-ryoya requested changes

2023-07-13 07:09 UTC, f-ryoya commented on apps/kita/routes/web.php
> +    Route::get('/admin_users/{admin_user}/edit', [AdminController::class, 'edit'])->name('admin_users.edit')->middleware('auth:admins');
ルーティングをグループしてmiddlewareを適用しているなら、個別のmiddlewareは不要です

2023-07-13 07:09 UTC, f-ryoya commented on apps/kita/routes/web.php
> +// prefix 外し
このコメントアウト不要ですね
ソースコードに残していたとして他の開発者が見た場合意図がわからず混乱すると思うので

2023-07-13 09:40 UTC, YoshikiWarashina commented on apps/kita/routes/web.php
> +    Route::get('/admin_users/{admin_user}/edit', [AdminController::class, 'edit'])->name('admin_users.edit')->middleware('auth:admins');
完全に見落としていました。修正しました。

2023-07-13 09:40 UTC, YoshikiWarashina commented on apps/kita/routes/web.php
> +// prefix 外し
修正しました。コメントアウトを消しました。

2023-07-18 14:30 UTC, f-ryoya approved these changes
LGTM!

2023-07-21 05:42 UTC, merged