article registration
YoshikiWarashina/Kita pull request #9
Opened 2023-07-07 13:13 UTC by YoshikiWarashina

後で書く

2023-07-13 07:40 UTC, f-ryoya commented
タグにバリデーションはいらないんですかね

2023-07-13 07:40 UTC, f-ryoya commented
> 記事投稿がデータベースに反映されるか

データベースに反映されてますか？このPRの動画からでは判断できないです

2023-07-13 07:48 UTC, f-ryoya requested changes

2023-07-13 07:48 UTC, f-ryoya commented on apps/kita/app/Services/ArticleService.php
> +     * 投稿後の記事を編集ページで表示
めっちゃ細かいですが、句点を書くのか書かないのか統一した方がいいかもです
コードの統一性のほつれにつながると個人的には思うので

2023-07-13 07:48 UTC, f-ryoya commented on apps/kita/routes/web.php
> +    Route::get('/{article_id}/edit', [ArticleController::class, 'edit'])->name('article.edit')->middleware('auth:members');
middlewareまとめられるかもですね

2023-07-13 09:29 UTC, YoshikiWarashina commented on apps/kita/app/Services/ArticleService.php
> +     * 投稿後の記事を編集ページで表示
修正しました。句読点は消す方向でいきます。

2023-07-13 09:29 UTC, YoshikiWarashina commented on apps/kita/routes/web.php
> +    Route::get('/{article_id}/edit', [ArticleController::class, 'edit'])->name('article.edit')->middleware('auth:members');
middlewareでまとめました。

2023-07-13 09:38 UTC, YoshikiWarashina commented
> タグにバリデーションはいらないんですかね

タグに関しての処理はまだ未着手なので後ほど行います。

> データベースに反映されてますか？このPRの動画からでは判断できないです

demo動画

https://github.com/YoshikiWarashina/Kita/assets/129946179/fe510155-5f8b-41df-a2e0-d28fa7100e24

登録後データベース

<img width="603" alt="スクリーンショット 2023-07-13 18 37 30" src="https://github.com/YoshikiWarashina/Kita/assets/129946179/32b2cd89-0c0c-4d7a-8fe7-0a7e98916965">

2023-07-18 14:32 UTC, f-ryoya commented
> タグにバリデーションはいらないんですかね

これは結局いらないという結論になったということかな？

2023-07-18 14:33 UTC, f-ryoya approved these changes
LGTM!

2023-07-21 05:17 UTC, merged